




ALTER TABLE public.appointment_cancelled ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.appointment_cancelled_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    MAXVALUE 2147483647
    CACHE 1
);



--
-- Name: invitation_professional; Type: TABLE; Schema: public; Owner: conmeddb_user
--

CREATE TABLE public.invitation_professional (
    id bigint NOT NULL,
    email text NOT NULL,
    colleague_name text
);


ALTER TABLE public.invitation_professional OWNER TO conmeddb_user;

--
-- Name: invitation_professional_id_seq; Type: SEQUENCE; Schema: public; Owner: conmeddb_user
--

ALTER TABLE public.invitation_professional ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.invitation_professional_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);






--
-- Name: invitation_professional invitation_professional_pkey; Type: CONSTRAINT; Schema: public; Owner: conmeddb_user
--

ALTER TABLE ONLY public.invitation_professional
    ADD CONSTRAINT invitation_professional_pkey PRIMARY KEY (id);



